import type { Metadata } from 'next'
import './globals.css'
import '@fontsource/poppins'
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
import { Toaster } from '@/components/ui/sonner'
import { ThemeProvider } from '@/components/themeProvider'

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <html lang="en" suppressHydrationWarning className="scroll-smooth">
                <head />
                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                    <Toaster />
                </body>
            </html>
        </>
    )
}
